export const START_GET_ARTICLES = 'START_GET_ARTICLES';
export const GET_ARTICLES = 'GET_ARTICLES';
export const SAVE_ARTICLES = 'SAVE_ARTICLES';
export const REQUEST_FAIL = 'REQUEST_FAIL';
export const SAVE_ARTICLE = 'SAVE_ARTICLE';

export const START_FETCH_AUTHOR = 'START_FETCH_AUTHOR';
export const SUCCESS_FETCH_AUTHOR = 'SUCCESS_FETCH_AUTHOR';
export const FAIL_FETCH_AUTHOR = 'FAIL_FETCH_AUTHOR';
export const UPDATE_LOCAL_AUTHOR_INFO = 'UPDATE_LOCAL_AUTHOR_INFO';

export const SUCCESS_FETCH_COMMENTS = 'SUCCESS_FETCH_COMMENTS';

export const START_ADD_COMMENT = 'START_ADD_COMMENT';
export const SUCCESS_ADD_COMMENT = 'SUCCESS_ADD_COMMENT';
export const FAIL_ADD_COMMENT = 'FAIL_ADD_COMMENT';

export const START_REMOVE_COMMENT = 'START_REMOVE_COMMENT';
export const SUCCESS_REMOVE_COMMENT = 'SUCCESS_REMOVE_COMMENT';
export const FAIL_REMOVE_COMMENT = 'FAIL_REMOVE_COMMENT';

export const START_LOGIN = 'START_LOGIN';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const FAIL_LOGIN = 'FAIL_LOGIN';

export const START_SIGNUP = 'START_SIGNUP';
export const SUCCESS_SIGNUP = 'SUCCESS_SIGNUP';
export const FAIL_SIGNUP = 'FAIL_SIGNUP';

export const LOGOUT = 'LOGOUT';